
from pymongo import MongoClient
from pymongo import errors
from pprint import pprint
# import json

client = MongoClient('127.0.0.1', 27017)
db = client['users100722']
persons = db.persons


##Задание 1. Развернуть у себя на компьютере/виртуальной машине/хостинге MongoDB
# #и реализовать функцию, которая будет добавлять только новые вакансии/продукты в вашу базу.


vacancies_list = [{'company_name': 'i20',
  'compensation': {'currency': 'руб', 'minimum': 30000},
  'href': 'https://makhachkala.hh.ru/vacancy/49090235?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Web-разработчик (стажер)',
  'website': 'hh.ru'},
{'company_name': 'Бизнес Пульс',
  'compensation': {'currency': 'руб', 'minimum': 20000},
  'href': 'https://makhachkala.hh.ru/vacancy/66890700?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0НПО Компас Здоровья',
  'compensation': {'currency': 'руб', 'maximum': 30000, 'minimum': 30000},
  'href': 'https://makhachkala.hh.ru/vacancy/67558366?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Завод Судовых Двигателей Ремдизель',
  'compensation': {'currency': 'руб', 'minimum': 20000},
  'href': 'https://makhachkala.hh.ru/vacancy/67389816?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Системный администратор/программист (стажер)',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Полюс Автоматика',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/67434409?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Инженер-программист (стажер) (АСУ ТП)',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Кайдзен-софт',
  'compensation': {'currency': 'руб', 'maximum': 70000, 'minimum': 30000},
  'href': 'https://makhachkala.hh.ru/vacancy/67051537?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажёр 1С',
  'website': 'hh.ru'},
 {'company_name': 'РАУ АйТи',
  'compensation': {'currency': 'руб', 'maximum': 60000, 'minimum': 20000},
  'href': 'https://makhachkala.hh.ru/vacancy/67375045?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'Business & Decision',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/67611259?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Айтиллект',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/67018699?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0НПФ Полисервис',
  'compensation': {'currency': 'руб', 'maximum': 50000, 'minimum': 40000},
  'href': 'https://makhachkala.hh.ru/vacancy/67136561?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Инженер разработчик (стажер)',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Комплексная Автоматизация Бизнеса',
  'compensation': {'currency': 'руб', 'minimum': 40000},
  'href': 'https://makhachkala.hh.ru/vacancy/67516534?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Внедренческий Центр Лис с',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/66838063?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'Go Masters',
  'compensation': {'currency': 'руб', 'maximum': 20000},
  'href': 'https://makhachkala.hh.ru/vacancy/67621029?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Go/Golang developer (стажёр)',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Лаборатория разработки приложений',
  'compensation': {'currency': 'руб', 'maximum': 25000, 'minimum': 15000},
  'href': 'https://makhachkala.hh.ru/vacancy/67293230?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер',
  'website': 'hh.ru'},
 {'company_name': 'Первый Бит',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/67408408?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'ALEXROVICH.RU',
  'compensation': {'currency': 'руб', 'minimum': 45000},
  'href': 'https://makhachkala.hh.ru/vacancy/66760060?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер',
  'website': 'hh.ru'},
 {'company_name': 'Адвантика,ООО',
  'compensation': {'currency': 'руб', 'minimum': 20000},
  'href': 'https://makhachkala.hh.ru/vacancy/66883287?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Веб-программист/стажер',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0ТК Приволжье-Транс',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/67335208?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'Арсан',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/67375957?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'Angels IT',
  'compensation': {'currency': 'руб', 'minimum': 30000},
  'href': 'https://makhachkala.hh.ru/vacancy/55373656?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Автоматизация Бизнеса',
  'compensation': {'currency': 'руб', 'maximum': 50000},
  'href': 'https://makhachkala.hh.ru/vacancy/67415796?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C (возможно удалённо)',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Акцент',
  'compensation': {'currency': 'руб', 'maximum': 70000, 'minimum': 45000},
  'href': 'https://makhachkala.hh.ru/vacancy/66527746?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0ИТВОРКС',
  'compensation': {'currency': 'руб', 'minimum': 35000},
  'href': 'https://makhachkala.hh.ru/vacancy/67500825?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1С (Москва)',
  'website': 'hh.ru'},
 {'company_name': 'Первый Бит',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/66087502?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Макшел-КМВ',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/66199268?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер',
  'website': 'hh.ru'},
 {'company_name': 'Гамма-Центр (банковское оборудование)',
  'compensation': {'currency': 'руб', 'maximum': 60000},
  'href': 'https://makhachkala.hh.ru/vacancy/53275467?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'Первый Бит',
  'compensation': {'currency': 'руб', 'minimum': 30000},
  'href': 'https://makhachkala.hh.ru/vacancy/67455218?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажёр 1С',
  'website': 'hh.ru'},
 {'company_name': 'Первый Бит',
  'compensation': {'currency': 'руб', 'maximum': 50000, 'minimum': 25000},
  'href': 'https://makhachkala.hh.ru/vacancy/51174735?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист - стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'РС Консалт',
  'compensation': {'currency': 'руб', 'minimum': 25000},
  'href': 'https://makhachkala.hh.ru/vacancy/46683160?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'Digital Design',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/66551839?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Разработчик-стажер (Linux, C)',
  'website': 'hh.ru'},
 {'company_name': 'Первый Бит',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/41537660?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Разработчик-стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'Первый Бит',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/66954793?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'ПАО «Газпром нефть»',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/52500839?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Junior веб-программист/Стажер (PHP, Bitrix)',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Ново Нордиск',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/67393174?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Стажер-программист/Intern',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Тольятти-софт',
  'compensation': {'currency': 'руб', 'maximum': 40000},
  'href': 'https://makhachkala.hh.ru/vacancy/66531643?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'ЮниВеб',
  'compensation': {'currency': 'руб', 'minimum': 20000},
  'href': 'https://makhachkala.hh.ru/vacancy/14694668?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Junior разработчик (стажер)',
  'website': 'hh.ru'},
 {'company_name': 'ИП\xa0Максаймер К.А (компания Эдванс)',
  'compensation': {'currency': 'KZT', 'maximum': 300000, 'minimum': 70000},
  'href': 'https://makhachkala.hh.ru/vacancy/67392724?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Разработчик/Стажер-разработчик на Java',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Деловое программное обеспечение',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/54500949?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажёр 1С',
  'website': 'hh.ru'},
 {'company_name': 'Первый Бит',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/66560508?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'ТОО\xa0Global-Systems',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/67395892?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Backend разработчик / стажёр (Java, Spring Boot)',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0ПКФ Атлантис-Пак',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/66947668?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист - стажёр 1C:ERP',
  'website': 'hh.ru'},
 {'company_name': 'Диарт',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/66815594?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'СофтБиз',
  'compensation': {'currency': 'руб', 'maximum': 45000, 'minimum': 30000},
  'href': 'https://makhachkala.hh.ru/vacancy/66805133?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'АО\xa0Строительная компания ФЛАН - М',
  'compensation': {'currency': 'руб', 'maximum': 80000, 'minimum': 60000},
  'href': 'https://makhachkala.hh.ru/vacancy/66143966?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Специалист - Техподдержки 1С / Консультант 1С (Программист-стажер '
          '1С)',
  'website': 'hh.ru'},
 {'company_name': '1С-Франчайзи Калидка',
  'compensation': {'currency': 'руб', 'maximum': 50000, 'minimum': 30000},
  'href': 'https://makhachkala.hh.ru/vacancy/66880327?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист, стажер 1С 8.3',
  'website': 'hh.ru'},
 {'company_name': 'DONTECO',
  'compensation': {'currency': 'руб', 'maximum': 50000, 'minimum': 40000},
  'href': 'https://makhachkala.hh.ru/vacancy/66782070?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Unreal Engine разработчик (стажер)',
  'website': 'hh.ru'},
 {'company_name': 'ПМК-Бухгалтер',
  'compensation': {'currency': 'руб', 'minimum': 30000},
  'href': 'https://makhachkala.hh.ru/vacancy/66833996?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Младший программист (стажер) 1С',
  'website': 'hh.ru'},
 {'company_name': 'СофтЭксперт, г. Тула',
  'compensation': {'currency': 'руб', 'minimum': 30000},
  'href': 'https://makhachkala.hh.ru/vacancy/32036712?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1С',
  'website': 'hh.ru'},
 {'company_name': 'ИП\xa0Чернов Эдуард Алексеевич',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/66768762?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Junior Vue.js developer (стажер)',
  'website': 'hh.ru'},
 {'company_name': 'ИП\xa0Рубцов Александр Юрьевич',
  'compensation': {'currency': 'руб', 'maximum': 50000, 'minimum': 25000},
  'href': 'https://makhachkala.hh.ru/vacancy/66760866?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'Нек. орг.\xa0Совет по развитию внешней торговли и '
                  'международных экономических отношений',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/66817510?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист/стажер по работе с Tilda',
  'website': 'hh.ru'},
 {'company_name': 'ТОО\xa0KaspiNet',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/67434934?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист стажер, FullStack',
  'website': 'hh.ru'},
 {'company_name': 'ТОО\xa0АПРО',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/52020544?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер',
  'website': 'hh.ru'},
 {'company_name': 'ООО\xa0Манао Дев',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/67350829?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'РНР developer/стажёр/intern',
  'website': 'hh.ru'},
 {'company_name': 'ИП\xa0IT Service',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/67223971?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'},
 {'company_name': 'ИП\xa0Мыслинская',
  'compensation': {'currency': 'KZT', 'minimum': 200000},
  'href': 'https://makhachkala.hh.ru/vacancy/66891340?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер/ Консультант 1C',
  'website': 'hh.ru'},
 {'company_name': 'ИП\xa0Серенков В.В.',
  'compensation': None,
  'href': 'https://makhachkala.hh.ru/vacancy/55318141?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=%22Programmer%20Intern%22',
  'name': 'Программист-стажер 1C',
  'website': 'hh.ru'}]

#
# try:
#    persons.insert_many(vacancies_list)
# except errors.DuplicateKeyError:
#     print(f"Document with id = {vacancies_list['href']} is already exists")
#



## 2. Написать функцию, которая производит поиск и выводит на экран вакансии с заработной платой больше введённой суммы
## (необходимо анализировать оба поля зарплаты). То есть цифра вводится одна, а запрос проверяет оба поля




 def find_vacancy(persons):
  salary = {'$or': [
                 {'minimum': {'$gt': 45000}},
                 {'maximum': {'$gt': 45000}}
                  ]}

  return list(persons.find_one(salary))

  pprint(find_vacancy(persons))




## or
# compensation_we_need = 45000
#
# for item in persons.find({'$or': [{"minimum": {"$gt": int(f"{compensation_we_need}")}},
#                                  {"maximum": {"$gt": int(f"{compensation_we_need}")}}]}):
#     pprint(item)